name: TikTok Bot Calistirici

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodlari Al
        uses: actions/checkout@v4

      - name: Python Kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Bagimliliklari Yukle ve Baslat
        run: |
          pip install TikTokLive aiohttp
          python main.py
          
